spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo-jpa?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: xinwuy
    password: chengxun